### ISSUE TITLE
JS Lint your code!

### ISSUE THREAD

**Issue by phlco** [DanaMC18/concentration-project1#2]
Hiya! I just ran your code through http://www.jshint.com

It can give you some helpful warnings about things to correct

Here's the output with the line numbers and problems.  See if any of these help!

```
Two warnings
83  Missing semicolon.
92  Missing semicolon.
One undefined variable
11  target
24  target
26  target
27  target
28  target
One unused variable
86  resetBoard
```

**Comment by DanaMC18** [comment]
Thanks Phil!

That's really helpful.
